# Generated by Django 5.2.14 on 2026-05-13 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('direccion_facturacion', models.TextField()),
                ('direccion_entrega_preferida', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='DispatchGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_guia', models.CharField(max_length=100, unique=True)),
                ('usa_direccion_facturacion', models.BooleanField(default=True)),
                ('direccion_entrega', models.TextField()),
                ('map_link', models.URLField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('emitida', 'Emitida'), ('asignada', 'Asignada'), ('en_ruta', 'En Ruta'), ('entregada', 'Entregada'), ('rechazada', 'Rechazada'), ('cerrada', 'Cerrada')], default='emitida', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guias', to='guides.client')),
                ('transportista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guias_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Guía de Despacho',
                'verbose_name_plural': 'Guías de Despacho',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='GuideStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('emitida', 'Emitida'), ('asignada', 'Asignada'), ('en_ruta', 'En Ruta'), ('entregada', 'Entregada'), ('rechazada', 'Rechazada'), ('cerrada', 'Cerrada')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='guide_photos/%Y/%m/%d/')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('guia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='guides.dispatchguide')),
            ],
            options={
                'verbose_name': 'Etapa de Guía',
                'verbose_name_plural': 'Etapas de Guías',
                'ordering': ['-timestamp'],
            },
        ),
    ]
