# Generated by Django 5.2.14 on 2026-05-14 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchguide',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guias_emitidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispatchguide',
            name='vendedor_nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
