# Generated by Django 5.2.14 on 2026-05-14 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0002_dispatchguide_vendedor_dispatchguide_vendedor_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vendedor / Asistente',
                'verbose_name_plural': 'Vendedores / Asistentes',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='dispatchguide',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guias_emitidas', to='guides.seller'),
        ),
    ]
