# Generated by Django 5.2.14 on 2026-05-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0003_seller_alter_dispatchguide_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchguide',
            name='nv',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nota de Venta'),
        ),
    ]
