# Generated by Django 5.2.14 on 2026-05-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0004_dispatchguide_nv'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchguide',
            name='fecha_despacho',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispatchguide',
            name='fecha_envio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
