# Generated by Django 5.2.14 on 2026-05-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0005_dispatchguide_fecha_despacho_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchguide',
            name='nv_fecha_creacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha creación NV'),
        ),
    ]
