# Generated by Django 5.2.15 on 2026-07-07 15:14

import guides.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0006_dispatchguide_nv_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidestage',
            name='foto',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=guides.models._guide_photo_path),
        ),
    ]
