# Generated by Django 5.2.14 on 2026-05-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0006_dispatchguide_nv_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidestage',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='tracking/guide_photos/%Y/%m/%d/'),
        ),
    ]
