# Generated by Django 5.2.14 on 2026-05-29 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0007_guidestage_foto_upload_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideStagePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='tracking/guide_photos/%Y/%m/%d/')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='guides.guidestage')),
            ],
            options={
                'verbose_name': 'Foto de Etapa',
                'verbose_name_plural': 'Fotos de Etapas',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
