# Generated by Django 5.2.15 on 2026-06-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0008_guidestagephoto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guidestagephoto',
            options={'ordering': ['categoria', 'orden', 'id'], 'verbose_name': 'Foto de Etapa', 'verbose_name_plural': 'Fotos de Etapas'},
        ),
        migrations.AddField(
            model_name='guidestagephoto',
            name='categoria',
            field=models.CharField(choices=[('guia', 'Guía de Despacho'), ('cliente', 'Cliente'), ('general', 'General')], default='general', max_length=20),
        ),
    ]
