# Generated by Django 5.2.15 on 2026-06-09 17:49

import guides.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0009_guidestagephoto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidestage',
            name='foto',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=guides.models._guide_photo_path),
        ),
        migrations.AlterField(
            model_name='guidestagephoto',
            name='foto',
            field=models.ImageField(max_length=500, upload_to=guides.models._guide_photo_path),
        ),
    ]
